export type AuditItem = {
  text: string;
  priority: 'P0' | 'P1' | 'P2';
  done?: boolean;
};

export type AuditSection = {
  id: string;
  title: string;
  icon: string;
  items: AuditItem[];
};

export const AUDIT_DATA: {
  generatedAt: string;
  sections: AuditSection[];
} = {
  generatedAt: '2026-05-28',
  sections: [
    {
      id: 'done',
      title: 'Już gotowe (Phase 1 + Phase 2)',
      icon: 'CheckCircle2',
      items: [
        { text: '76 stron statycznych SEO (miasto × kategoria)', priority: 'P0', done: true },
        { text: 'Orchestrator AI — dashboard 11 agentów / 1000 tasków', priority: 'P1', done: true },
        { text: 'Marketplace: 5 kategorii (zakłady, kwiaciarnie, kamieniarze, krematoria, transport)', priority: 'P0', done: true },
        { text: 'Booking stepper (6 kroków) na /rezerwacja/[kategoria]', priority: 'P0', done: true },
        { text: 'AI chat widget (grief-safe prompty)', priority: 'P1', done: true },
        { text: 'Meilisearch — klient + endpoint /api/search + UI /szukaj', priority: 'P1', done: true },
        { text: 'Schema.org JSON-LD (8 generatorów) + sitemap.xml + robots.txt', priority: 'P0', done: true },
        { text: 'Docker compose (Postgres, Auth, Kong, Storage, Meili, Redis, MinIO, Traefik)', priority: 'P0', done: true },
        { text: 'Stripe webhook (skeleton) + Resend (email) + SMSAPI (sms)', priority: 'P0', done: true },
        { text: 'Design system + tokens (cream/navy/green/gold + Lora/Inter)', priority: 'P0', done: true },
      ],
    },
    {
      id: 'auth',
      title: 'Auth & Security (P0)',
      icon: 'Lock',
      items: [
        { text: 'Pełny flow Supabase Auth: email+password, Google OAuth, magic link', priority: 'P0' },
        { text: 'Middleware ochrony /panel-firmy/*, /panel-rodziny/*, /admin/*', priority: 'P0' },
        { text: 'SSR session refresh + cookie HttpOnly/Secure/SameSite=Lax', priority: 'P0' },
        { text: 'CSRF tokeny na wszystkich POST', priority: 'P0' },
        { text: 'Rate limiting na produkcji (Upstash Redis zamiast in-memory)', priority: 'P0' },
        { text: 'Cloudflare Turnstile na /zapytanie, /api/lead, /api/booking', priority: 'P0' },
        { text: 'CSP, HSTS, X-Frame-Options, X-Content-Type-Options w next.config', priority: 'P0' },
        { text: 'RLS policy verification + audyt SQL injections', priority: 'P0' },
        { text: 'Audit log (kto, co, kiedy) → tabela audit_logs', priority: 'P0' },
        { text: 'Password reset flow + email weryfikacji', priority: 'P0' },
        { text: '2FA opcjonalne (TOTP) dla admin/firma', priority: 'P1' },
        { text: 'Session timeout + logout all devices', priority: 'P1' },
      ],
    },
    {
      id: 'payments',
      title: 'Płatności (P0)',
      icon: 'CreditCard',
      items: [
        { text: '/api/checkout/subscription — Stripe Checkout per plan (Solo/Pro/Plus)', priority: 'P0' },
        { text: '/api/checkout/booking — płatność za rezerwację', priority: 'P0' },
        { text: 'Stripe Customer Portal (zarządzanie subskrypcją)', priority: 'P0' },
        { text: 'Przelewy24 + BLIK integracja + webhook', priority: 'P0' },
        { text: 'Generator faktur PDF (pdfkit / react-pdf)', priority: 'P0' },
        { text: 'Tabela invoices + numeracja sekwencyjna FA/2026/01', priority: 'P0' },
        { text: 'Wysyłka faktur email (Resend)', priority: 'P0' },
        { text: 'Przedłużanie subskrypcji + grace period 7 dni', priority: 'P0' },
        { text: 'Refund flow + half-refund (po 14 dniach mniejszy)', priority: 'P1' },
        { text: 'Stripe Tax / VAT EU automatyczne naliczanie', priority: 'P1' },
        { text: 'Strona /cennik (3 plany) + porównanie funkcji', priority: 'P0' },
      ],
    },
    {
      id: 'panels',
      title: 'Panel firmy (P0)',
      icon: 'Building2',
      items: [
        { text: '/panel-firmy/dashboard — statystyki, ostatnie leady, ROI', priority: 'P0' },
        { text: '/panel-firmy/profil — edycja CMS (galeria, opis, godziny)', priority: 'P0' },
        { text: '/panel-firmy/cennik — edytor pakietów', priority: 'P0' },
        { text: '/panel-firmy/galeria — upload do Supabase Storage + crop', priority: 'P0' },
        { text: '/panel-firmy/leady — inbox + status (nowy/kontakt/zamknięty)', priority: 'P0' },
        { text: '/panel-firmy/rezerwacje — kalendarz + slot management', priority: 'P0' },
        { text: '/panel-firmy/wiadomosci — czat z rodziną (Realtime)', priority: 'P0' },
        { text: '/panel-firmy/opinie — widok + odpowiedzi', priority: 'P0' },
        { text: '/panel-firmy/dokumenty — KRS/NIP, polisy, certyfikaty', priority: 'P0' },
        { text: '/panel-firmy/zespol — multi-user (właściciel + pracownik)', priority: 'P1' },
        { text: '/panel-firmy/integracje — webhooks, API key, kalendarz Google', priority: 'P1' },
        { text: '/panel-firmy/ustawienia — powiadomienia, hasło, faktura', priority: 'P0' },
      ],
    },
    {
      id: 'family',
      title: 'Panel rodziny (P0)',
      icon: 'Heart',
      items: [
        { text: '/panel-rodziny/dashboard — moje zapytania, rezerwacje, dokumenty', priority: 'P0' },
        { text: '/panel-rodziny/zapytania — historia + statusy', priority: 'P0' },
        { text: '/panel-rodziny/wiadomosci — czat z firmami', priority: 'P0' },
        { text: '/panel-rodziny/dokumenty — akt zgonu upload + share', priority: 'P0' },
        { text: '/panel-rodziny/nekrolog — kreator nekrologu (free + premium)', priority: 'P1' },
        { text: '/panel-rodziny/zaloba — wsparcie po pogrzebie (artykuły, helpline)', priority: 'P1' },
        { text: 'Konto rodziny: rejestracja przez magic link (bez hasła)', priority: 'P0' },
      ],
    },
    {
      id: 'admin',
      title: 'Panel admin (P0)',
      icon: 'Shield',
      items: [
        { text: '/admin/dashboard — KPI: nowi userzy, MRR, churn, leady, NPS', priority: 'P0' },
        { text: '/admin/firmy — lista + moderacja + suspend', priority: 'P0' },
        { text: '/admin/weryfikacje — kolejka KRS/NIP + akceptacja', priority: 'P0' },
        { text: '/admin/opinie — moderacja zgłoszonych', priority: 'P0' },
        { text: '/admin/leady — wszystkie + przypisanie + jakość', priority: 'P0' },
        { text: '/admin/uzytkownicy — wyszukiwarka + impersonate (audytowane)', priority: 'P0' },
        { text: '/admin/faktury — generowanie + wysyłka + korekty', priority: 'P0' },
        { text: '/admin/raporty — eksport CSV/Excel', priority: 'P1' },
        { text: '/admin/cms — edycja stron statycznych + artykułów', priority: 'P1' },
        { text: '/admin/audyt — log wszystkich akcji adminów', priority: 'P0' },
        { text: '/admin/feature-flags — włączanie funkcji per cohort', priority: 'P2' },
      ],
    },
    {
      id: 'data',
      title: 'Dane & geo (P1)',
      icon: 'MapPin',
      items: [
        { text: 'PostGIS — geo-search w promieniu N km od kodu pocztowego', priority: 'P1' },
        { text: 'Geocoding (Nominatim / Google Maps) — adres → lat/lng', priority: 'P1' },
        { text: 'Mapa z markerami (MapLibre + OpenStreetMap, no Google fees)', priority: 'P1' },
        { text: 'Autocomplete adresów (Mapbox / OSM Photon)', priority: 'P1' },
        { text: 'Routing — czas dojazdu (OSRM)', priority: 'P2' },
        { text: 'Slug normalizacja Polska (warszawa, krakow, ml. zamosc)', priority: 'P1' },
        { text: 'Import bazy CEIDG / GUS REGON — automatyczne zakładanie wizytówek', priority: 'P1' },
      ],
    },
    {
      id: 'ai',
      title: 'AI & Personalizacja (P1)',
      icon: 'Sparkles',
      items: [
        { text: 'Streaming AI responses (Vercel AI SDK + edge runtime)', priority: 'P1' },
        { text: 'pgvector — embedding firm + semantic search', priority: 'P1' },
        { text: 'AI matcher — top 3 firmy dopasowane do rodziny', priority: 'P1' },
        { text: 'Moderacja AI (OpenAI moderation API) na wszystkie inputy', priority: 'P0' },
        { text: 'Crisis detection — przekierowanie do 116 123 (Telefon Zaufania)', priority: 'P0' },
        { text: 'AI content generator dla firm (opis profilu, pakiety)', priority: 'P2' },
        { text: 'AI recap of conversation → handoff do agenta', priority: 'P2' },
      ],
    },
    {
      id: 'monitoring',
      title: 'Monitoring & DevOps (P0)',
      icon: 'Activity',
      items: [
        { text: 'Sentry — error tracking front + back + source maps', priority: 'P0' },
        { text: 'Grafana + Prometheus — metryki app', priority: 'P0' },
        { text: 'Loki — centralne logi', priority: 'P0' },
        { text: 'Uptime Kuma — uptime monitor + alerty', priority: 'P0' },
        { text: 'PagerDuty / Opsgenie — on-call rotation', priority: 'P1' },
        { text: 'Backup Postgres co 6h → S3 (MinIO + Wasabi offsite)', priority: 'P0' },
        { text: 'DR runbook — restore from backup w <2h', priority: 'P0' },
        { text: 'CI: lint + typecheck + unit + e2e + lighthouse', priority: 'P0' },
        { text: 'CD: deploy preview na PR + auto-deploy main', priority: 'P0' },
        { text: 'Container scan (Trivy) + dependency audit (Dependabot)', priority: 'P0' },
        { text: 'Rotating secrets (HashiCorp Vault / Doppler)', priority: 'P1' },
      ],
    },
    {
      id: 'qa',
      title: 'QA & Testing (P0)',
      icon: 'TestTube',
      items: [
        { text: 'Vitest — unit tests, coverage gate ≥80%', priority: 'P0' },
        { text: 'Playwright — 10 happy paths E2E', priority: 'P0' },
        { text: 'axe-core — automated a11y testing', priority: 'P0' },
        { text: 'Percy / Chromatic — visual regression', priority: 'P1' },
        { text: 'k6 — load test 1000 RPS na search + booking', priority: 'P0' },
        { text: 'MSW — mock service worker dla API w testach', priority: 'P1' },
        { text: 'OWASP ZAP — security scan w CI', priority: 'P0' },
        { text: 'Lighthouse CI — gate ≥90 mobile/desktop', priority: 'P0' },
        { text: 'Pen-test zewnętrzny przed launch', priority: 'P0' },
        { text: 'Smoke tests po deploy na prod', priority: 'P0' },
      ],
    },
    {
      id: 'content',
      title: 'Content & SEO (P1)',
      icon: 'PenLine',
      items: [
        { text: '30+ artykułów eksperckich (1500+ słów każdy)', priority: 'P1' },
        { text: 'FAQ — 50 pytań z FAQPage schema', priority: 'P1' },
        { text: 'Glosariusz — 100 pojęć funeralnych', priority: 'P1' },
        { text: 'Magnesy: PDF "10 kroków po stracie" + checklist', priority: 'P1' },
        { text: 'Email sekwencje (welcome 5x, win-back, retention)', priority: 'P1' },
        { text: 'Microcopy audit — wszystkie CTA, błędy, komunikaty', priority: 'P1' },
        { text: 'Translacje EN/UA (opcjonalnie po launchu)', priority: 'P2' },
      ],
    },
    {
      id: 'compliance',
      title: 'Zgodność prawna (P0)',
      icon: 'FileText',
      items: [
        { text: 'Regulamin serwisu (B2B + B2C) — sprawdzony przez prawnika', priority: 'P0' },
        { text: 'Polityka prywatności + RODO compliance', priority: 'P0' },
        { text: 'Polityka cookies + CMP (cookiebot / klaro)', priority: 'P0' },
        { text: 'DPA z subprocessorami (Supabase, Stripe, Resend, Cloudflare)', priority: 'P0' },
        { text: 'Right to delete / export (GDPR Art. 15-17)', priority: 'P0' },
        { text: 'Konsumencki — 14 dni odstąpienia (B2C)', priority: 'P0' },
        { text: 'Rejestr czynności przetwarzania (RCP)', priority: 'P0' },
        { text: 'Klauzula ESG / dostępność WCAG 2.2 AA deklaracja', priority: 'P1' },
      ],
    },
    {
      id: 'launch',
      title: 'Launch readiness (P0)',
      icon: 'Rocket',
      items: [
        { text: 'Lighthouse ≥90 mobile na wszystkich kluczowych stronach', priority: 'P0' },
        { text: 'CWV: LCP <2.5s, INP <200ms, CLS <0.1', priority: 'P0' },
        { text: '10 happy paths E2E passing zielone', priority: 'P0' },
        { text: 'Pen-test OWASP Top 10 — zero high/critical', priority: 'P0' },
        { text: 'Load test 1000 RPS — search + booking', priority: 'P0' },
        { text: 'Backup verified — restore test wykonany', priority: 'P0' },
        { text: 'DR runbook — opisany i przećwiczony', priority: 'P0' },
        { text: 'GDPR compliant — DPIA wykonana', priority: 'P0' },
        { text: 'Cookie banner + Plausible + opcjonalny PostHog', priority: 'P0' },
        { text: 'Status page (status.polskiepogrzeby.pl)', priority: 'P1' },
        { text: '50 firm zalogowanych w pre-launch (Beta)', priority: 'P1' },
      ],
    },
  ],
};
